version: '3.1'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  mysql_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=flaskchest
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: